<?xml version="1.0"?>
<robot name="wheeltec_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


        <xacro:property name="imu_offset_x" value="0.02" />
        <xacro:property name="imu_offset_y" value="0.02" />
        <xacro:property name="imu_offset_z" value="0.02" />
        <xacro:property name="imu_m" value="0.01" /> <!-- imu质量 -->
        <link name="imu">
            <visual>
                <geometry>
                    <box size="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            </collision>
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="${imu_m}" />
                <inertia ixx="${imu_m*(imu_offset_z*imu_offset_z + imu_offset_x*imu_offset_x)/12}" ixy = "0" ixz = "0"
                        iyy="${imu_m*(imu_offset_y*imu_offset_y + imu_offset_x*imu_offset_x)/12}" iyz= "0"
                        izz="${imu_m*(imu_offset_y*imu_offset_y + imu_offset_z*imu_offset_z)/12}" />
            </inertial>
        </link>

        <xacro:property name="column_lidar_imu_x" value="0.1" />
        <xacro:property name="column_lidar_imu_y" value="0.1" />
        <xacro:property name="column_lidar_imu_z" value="0.3" />
        <xacro:property name="column_lidar_imu_m" value="0.5" /> 
        <link name="column_lidar_imu_link">
            <visual>
                <geometry>
                    <box size="${column_lidar_imu_x} ${column_lidar_imu_y} ${column_lidar_imu_z}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${column_lidar_imu_x} ${column_lidar_imu_y} ${column_lidar_imu_z}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            </collision>
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="${column_lidar_imu_m}" />
                <inertia ixx="${column_lidar_imu_m*(column_lidar_imu_z*column_lidar_imu_z + column_lidar_imu_x*column_lidar_imu_x)/12}" ixy = "0" ixz = "0"
                        iyy="${column_lidar_imu_m*(column_lidar_imu_y*column_lidar_imu_y + column_lidar_imu_x*column_lidar_imu_x)/12}" iyz= "0"
                        izz="${column_lidar_imu_m*(column_lidar_imu_y*column_lidar_imu_y + column_lidar_imu_z*column_lidar_imu_z)/12}" />
            </inertial>
        </link>

        <joint name="column_imu_lidar_joint" type="fixed">
            <parent link="two_ply_link" />
            <child link="column_lidar_imu_link" />
            <origin xyz="${base_size_x / 2 - column_lidar_imu_x / 2} 0 ${column_lidar_imu_z / 2 + base_size_z / 2}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <joint name="imu_joint" type="fixed">
            <parent link="base_link" />
            <child link="imu" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 0 1" />
        </joint>

        
</robot>
